"""add qr_code

Revision ID: 6c5c7fb5569d
Revises: 895abc28daeb
Create Date: 2024-02-27 13:19:15.511290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5c7fb5569d'
down_revision: Union[str, None] = '895abc28daeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM('admin','moderator', 'user')")
    op.add_column('users', sa.Column('roles',
                                     sa.Enum('admin', 'moderator', 'user', name='role'),
                                     nullable=True, default='user'))
    op.add_column('images', sa.Column('qr_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    op.execute("DROP TYPE role")
    op.drop_column('images', 'qr_url')
    # ### end Alembic commands ###
